version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "8082:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"

  produit-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: produit-container
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/product
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING.JPA.HIBERNATE.DDL_AUTO: update
    depends_on:
      - db